/** @file cmdline.h
 *  @brief The header file for the command line option parser
 *  generated by GNU Gengetopt version 2.22
 *  http://www.gnu.org/software/gengetopt.
 *  DO NOT modify this file, since it can be overwritten
 *  @author GNU Gengetopt by Lorenzo Bettini */

#ifndef CMDLINE_H
#define CMDLINE_H

/* If we use autoconf.  */
#ifdef HAVE_CONFIG_H
#include "config.h"
#endif

#include <stdio.h> /* for FILE */

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#ifndef CMDLINE_PARSER_PACKAGE
/** @brief the program name */
#define CMDLINE_PARSER_PACKAGE "Funcaeologist"
#endif

#ifndef CMDLINE_PARSER_VERSION
/** @brief the program version */
#define CMDLINE_PARSER_VERSION "1.0"
#endif

/** @brief Where the command line options are stored */
struct gengetopt_args_info
{
  const char *help_help; /**< @brief Print help and exit help description.  */
  const char *version_help; /**< @brief Print version and exit help description.  */
  char * genes_arg;	/**< @brief Gene set to investigate.  */
  char * genes_orig;	/**< @brief Gene set to investigate original value given at command line.  */
  const char *genes_help; /**< @brief Gene set to investigate help description.  */
  char * directory_arg;	/**< @brief DAB network file directory (default='.').  */
  char * directory_orig;	/**< @brief DAB network file directory original value given at command line.  */
  const char *directory_help; /**< @brief DAB network file directory help description.  */
  char * input_arg;	/**< @brief DAT/DAB file in which backgrounds are calculated.  */
  char * input_orig;	/**< @brief DAT/DAB file in which backgrounds are calculated original value given at command line.  */
  const char *input_help; /**< @brief DAT/DAB file in which backgrounds are calculated help description.  */
  char * input_within_arg;	/**< @brief If given, DAT/DAB file in which within edges are calculated.  */
  char * input_within_orig;	/**< @brief If given, DAT/DAB file in which within edges are calculated original value given at command line.  */
  const char *input_within_help; /**< @brief If given, DAT/DAB file in which within edges are calculated help description.  */
  char * sizes_arg;	/**< @brief Text file containing set sizes to test.  */
  char * sizes_orig;	/**< @brief Text file containing set sizes to test original value given at command line.  */
  const char *sizes_help; /**< @brief Text file containing set sizes to test help description.  */
  int count_arg;	/**< @brief Number of random gene sets to test per size (default='100').  */
  char * count_orig;	/**< @brief Number of random gene sets to test per size original value given at command line.  */
  const char *count_help; /**< @brief Number of random gene sets to test per size help description.  */
  int invgauss_flag;	/**< @brief Compute inverse gaussian lambda instead of stdev (default=off).  */
  const char *invgauss_help; /**< @brief Compute inverse gaussian lambda instead of stdev help description.  */
  double percentile_arg;	/**< @brief Percentile to use for p-value cutoff (default='0.95').  */
  char * percentile_orig;	/**< @brief Percentile to use for p-value cutoff original value given at command line.  */
  const char *percentile_help; /**< @brief Percentile to use for p-value cutoff help description.  */
  int singles_flag;	/**< @brief Process single sets rather than pairs (default=off).  */
  const char *singles_help; /**< @brief Process single sets rather than pairs help description.  */
  int normalize_flag;	/**< @brief Normalize to the range [0,1] (default=off).  */
  const char *normalize_help; /**< @brief Normalize to the range [0,1] help description.  */
  int threads_arg;	/**< @brief Number of simultaneous threads (default='1').  */
  char * threads_orig;	/**< @brief Number of simultaneous threads original value given at command line.  */
  const char *threads_help; /**< @brief Number of simultaneous threads help description.  */
  int memmap_flag;	/**< @brief Memory map input (default=off).  */
  const char *memmap_help; /**< @brief Memory map input help description.  */
  int random_arg;	/**< @brief Seed random generator (default='0').  */
  char * random_orig;	/**< @brief Seed random generator original value given at command line.  */
  const char *random_help; /**< @brief Seed random generator help description.  */
  int verbosity_arg;	/**< @brief Message verbosity (default='5').  */
  char * verbosity_orig;	/**< @brief Message verbosity original value given at command line.  */
  const char *verbosity_help; /**< @brief Message verbosity help description.  */
  
  unsigned int help_given ;	/**< @brief Whether help was given.  */
  unsigned int version_given ;	/**< @brief Whether version was given.  */
  unsigned int genes_given ;	/**< @brief Whether genes was given.  */
  unsigned int directory_given ;	/**< @brief Whether directory was given.  */
  unsigned int input_given ;	/**< @brief Whether input was given.  */
  unsigned int input_within_given ;	/**< @brief Whether input_within was given.  */
  unsigned int sizes_given ;	/**< @brief Whether sizes was given.  */
  unsigned int count_given ;	/**< @brief Whether count was given.  */
  unsigned int invgauss_given ;	/**< @brief Whether invgauss was given.  */
  unsigned int percentile_given ;	/**< @brief Whether percentile was given.  */
  unsigned int singles_given ;	/**< @brief Whether singles was given.  */
  unsigned int normalize_given ;	/**< @brief Whether normalize was given.  */
  unsigned int threads_given ;	/**< @brief Whether threads was given.  */
  unsigned int memmap_given ;	/**< @brief Whether memmap was given.  */
  unsigned int random_given ;	/**< @brief Whether random was given.  */
  unsigned int verbosity_given ;	/**< @brief Whether verbosity was given.  */

  char **inputs ; /**< @brief unamed options (options without names) */
  unsigned inputs_num ; /**< @brief unamed options number */
} ;

/** @brief The additional parameters to pass to parser functions */
struct cmdline_parser_params
{
  int override; /**< @brief whether to override possibly already present options (default 0) */
  int initialize; /**< @brief whether to initialize the option structure gengetopt_args_info (default 1) */
  int check_required; /**< @brief whether to check that all required options were provided (default 1) */
  int check_ambiguity; /**< @brief whether to check for options already specified in the option structure gengetopt_args_info (default 0) */
  int print_errors; /**< @brief whether getopt_long should print an error message for a bad option (default 1) */
} ;

/** @brief the purpose string of the program */
extern const char *gengetopt_args_info_purpose;
/** @brief the usage string of the program */
extern const char *gengetopt_args_info_usage;
/** @brief all the lines making the help output */
extern const char *gengetopt_args_info_help[];

/**
 * The command line parser
 * @param argc the number of command line options
 * @param argv the command line options
 * @param args_info the structure where option information will be stored
 * @return 0 if everything went fine, NON 0 if an error took place
 */
int cmdline_parser (int argc, char * const *argv,
  struct gengetopt_args_info *args_info);

/**
 * The command line parser (version with additional parameters - deprecated)
 * @param argc the number of command line options
 * @param argv the command line options
 * @param args_info the structure where option information will be stored
 * @param override whether to override possibly already present options
 * @param initialize whether to initialize the option structure my_args_info
 * @param check_required whether to check that all required options were provided
 * @return 0 if everything went fine, NON 0 if an error took place
 * @deprecated use cmdline_parser_ext() instead
 */
int cmdline_parser2 (int argc, char * const *argv,
  struct gengetopt_args_info *args_info,
  int override, int initialize, int check_required);

/**
 * The command line parser (version with additional parameters)
 * @param argc the number of command line options
 * @param argv the command line options
 * @param args_info the structure where option information will be stored
 * @param params additional parameters for the parser
 * @return 0 if everything went fine, NON 0 if an error took place
 */
int cmdline_parser_ext (int argc, char * const *argv,
  struct gengetopt_args_info *args_info,
  struct cmdline_parser_params *params);

/**
 * Save the contents of the option struct into an already open FILE stream.
 * @param outfile the stream where to dump options
 * @param args_info the option struct to dump
 * @return 0 if everything went fine, NON 0 if an error took place
 */
int cmdline_parser_dump(FILE *outfile,
  struct gengetopt_args_info *args_info);

/**
 * Save the contents of the option struct into a (text) file.
 * This file can be read by the config file parser (if generated by gengetopt)
 * @param filename the file where to save
 * @param args_info the option struct to save
 * @return 0 if everything went fine, NON 0 if an error took place
 */
int cmdline_parser_file_save(const char *filename,
  struct gengetopt_args_info *args_info);

/**
 * Print the help
 */
void cmdline_parser_print_help(void);
/**
 * Print the version
 */
void cmdline_parser_print_version(void);

/**
 * Initializes all the fields a cmdline_parser_params structure 
 * to their default values
 * @param params the structure to initialize
 */
void cmdline_parser_params_init(struct cmdline_parser_params *params);

/**
 * Allocates dynamically a cmdline_parser_params structure and initializes
 * all its fields to their default values
 * @return the created and initialized cmdline_parser_params structure
 */
struct cmdline_parser_params *cmdline_parser_params_create(void);

/**
 * Initializes the passed gengetopt_args_info structure's fields
 * (also set default values for options that have a default)
 * @param args_info the structure to initialize
 */
void cmdline_parser_init (struct gengetopt_args_info *args_info);
/**
 * Deallocates the string fields of the gengetopt_args_info structure
 * (but does not deallocate the structure itself)
 * @param args_info the structure to deallocate
 */
void cmdline_parser_free (struct gengetopt_args_info *args_info);

/**
 * Checks that all the required options were specified
 * @param args_info the structure to check
 * @param prog_name the name of the program that will be used to print
 *   possible errors
 * @return
 */
int cmdline_parser_required (struct gengetopt_args_info *args_info,
  const char *prog_name);


#ifdef __cplusplus
}
#endif /* __cplusplus */
#endif /* CMDLINE_H */
