/** @file cmdline.h
 *  @brief The header file for the command line option parser
 *  generated by GNU Gengetopt version 2.22.5
 *  http://www.gnu.org/software/gengetopt.
 *  DO NOT modify this file, since it can be overwritten
 *  @author GNU Gengetopt by Lorenzo Bettini */

#ifndef CMDLINE_H
#define CMDLINE_H

/* If we use autoconf.  */
#ifdef HAVE_CONFIG_H
#include "config.h"
#endif

#include <stdio.h> /* for FILE */

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#ifndef CMDLINE_PARSER_PACKAGE
/** @brief the program name (used for printing errors) */
#define CMDLINE_PARSER_PACKAGE "Contexter"
#endif

#ifndef CMDLINE_PARSER_PACKAGE_NAME
/** @brief the complete program name (used for help and version) */
#define CMDLINE_PARSER_PACKAGE_NAME "Contexter"
#endif

#ifndef CMDLINE_PARSER_VERSION
/** @brief the program version */
#define CMDLINE_PARSER_VERSION "1.0"
#endif

/** @brief Where the command line options are stored */
struct gengetopt_args_info
{
  const char *help_help; /**< @brief Print help and exit help description.  */
  const char *version_help; /**< @brief Print version and exit help description.  */
  char * input_arg;	/**< @brief DAT/DAB file or context IDs and names.  */
  char * input_orig;	/**< @brief DAT/DAB file or context IDs and names original value given at command line.  */
  const char *input_help; /**< @brief DAT/DAB file or context IDs and names help description.  */
  int dat_flag;	/**< @brief Use DAT/DAB file input rather than Bayes nets (default=off).  */
  const char *dat_help; /**< @brief Use DAT/DAB file input rather than Bayes nets help description.  */
  char * database_arg;	/**< @brief Database directory (default='.').  */
  char * database_orig;	/**< @brief Database directory original value given at command line.  */
  const char *database_help; /**< @brief Database directory help description.  */
  char * contexts_arg;	/**< @brief Context/gene mapping.  */
  char * contexts_orig;	/**< @brief Context/gene mapping original value given at command line.  */
  const char *contexts_help; /**< @brief Context/gene mapping help description.  */
  int context_arg;	/**< @brief Context ID to process.  */
  char * context_orig;	/**< @brief Context ID to process original value given at command line.  */
  const char *context_help; /**< @brief Context ID to process help description.  */
  char * genes_arg;	/**< @brief Gene ID to name mapping.  */
  char * genes_orig;	/**< @brief Gene ID to name mapping original value given at command line.  */
  const char *genes_help; /**< @brief Gene ID to name mapping help description.  */
  int is_nibble_arg;	/**< @brief Define whether the database is nibble type. (default='1').  */
  char * is_nibble_orig;	/**< @brief Define whether the database is nibble type. original value given at command line.  */
  const char *is_nibble_help; /**< @brief Define whether the database is nibble type. help description.  */
  char * networks_arg;	/**< @brief Bayes net directory (default='.').  */
  char * networks_orig;	/**< @brief Bayes net directory original value given at command line.  */
  const char *networks_help; /**< @brief Bayes net directory help description.  */
  char * default_arg;	/**< @brief Bayes net for no context.  */
  char * default_orig;	/**< @brief Bayes net for no context original value given at command line.  */
  const char *default_help; /**< @brief Bayes net for no context help description.  */
  int xdsl_flag;	/**< @brief Use XDSL files instead of DSL (default=on).  */
  const char *xdsl_help; /**< @brief Use XDSL files instead of DSL help description.  */
  int minimal_in_flag;	/**< @brief Read stored contexts and minimal Bayes nets (default=off).  */
  const char *minimal_in_help; /**< @brief Read stored contexts and minimal Bayes nets help description.  */
  char * minimal_out_arg;	/**< @brief Store contexts and minimal Bayes nets.  */
  char * minimal_out_orig;	/**< @brief Store contexts and minimal Bayes nets original value given at command line.  */
  const char *minimal_out_help; /**< @brief Store contexts and minimal Bayes nets help description.  */
  char * lookup_arg;	/**< @brief Gene name to lookup.  */
  char * lookup_orig;	/**< @brief Gene name to lookup original value given at command line.  */
  const char *lookup_help; /**< @brief Gene name to lookup help description.  */
  int memmap_flag;	/**< @brief Memory map input (default=off).  */
  const char *memmap_help; /**< @brief Memory map input help description.  */
  int verbosity_arg;	/**< @brief Message verbosity (default='5').  */
  char * verbosity_orig;	/**< @brief Message verbosity original value given at command line.  */
  const char *verbosity_help; /**< @brief Message verbosity help description.  */
  
  unsigned int help_given ;	/**< @brief Whether help was given.  */
  unsigned int version_given ;	/**< @brief Whether version was given.  */
  unsigned int input_given ;	/**< @brief Whether input was given.  */
  unsigned int dat_given ;	/**< @brief Whether dat was given.  */
  unsigned int database_given ;	/**< @brief Whether database was given.  */
  unsigned int contexts_given ;	/**< @brief Whether contexts was given.  */
  unsigned int context_given ;	/**< @brief Whether context was given.  */
  unsigned int genes_given ;	/**< @brief Whether genes was given.  */
  unsigned int is_nibble_given ;	/**< @brief Whether is_nibble was given.  */
  unsigned int networks_given ;	/**< @brief Whether networks was given.  */
  unsigned int default_given ;	/**< @brief Whether default was given.  */
  unsigned int xdsl_given ;	/**< @brief Whether xdsl was given.  */
  unsigned int minimal_in_given ;	/**< @brief Whether minimal_in was given.  */
  unsigned int minimal_out_given ;	/**< @brief Whether minimal_out was given.  */
  unsigned int lookup_given ;	/**< @brief Whether lookup was given.  */
  unsigned int memmap_given ;	/**< @brief Whether memmap was given.  */
  unsigned int verbosity_given ;	/**< @brief Whether verbosity was given.  */

  char **inputs ; /**< @brief unamed options (options without names) */
  unsigned inputs_num ; /**< @brief unamed options number */
} ;

/** @brief The additional parameters to pass to parser functions */
struct cmdline_parser_params
{
  int override; /**< @brief whether to override possibly already present options (default 0) */
  int initialize; /**< @brief whether to initialize the option structure gengetopt_args_info (default 1) */
  int check_required; /**< @brief whether to check that all required options were provided (default 1) */
  int check_ambiguity; /**< @brief whether to check for options already specified in the option structure gengetopt_args_info (default 0) */
  int print_errors; /**< @brief whether getopt_long should print an error message for a bad option (default 1) */
} ;

/** @brief the purpose string of the program */
extern const char *gengetopt_args_info_purpose;
/** @brief the usage string of the program */
extern const char *gengetopt_args_info_usage;
/** @brief all the lines making the help output */
extern const char *gengetopt_args_info_help[];

/**
 * The command line parser
 * @param argc the number of command line options
 * @param argv the command line options
 * @param args_info the structure where option information will be stored
 * @return 0 if everything went fine, NON 0 if an error took place
 */
int cmdline_parser (int argc, char **argv,
  struct gengetopt_args_info *args_info);

/**
 * The command line parser (version with additional parameters - deprecated)
 * @param argc the number of command line options
 * @param argv the command line options
 * @param args_info the structure where option information will be stored
 * @param override whether to override possibly already present options
 * @param initialize whether to initialize the option structure my_args_info
 * @param check_required whether to check that all required options were provided
 * @return 0 if everything went fine, NON 0 if an error took place
 * @deprecated use cmdline_parser_ext() instead
 */
int cmdline_parser2 (int argc, char **argv,
  struct gengetopt_args_info *args_info,
  int override, int initialize, int check_required);

/**
 * The command line parser (version with additional parameters)
 * @param argc the number of command line options
 * @param argv the command line options
 * @param args_info the structure where option information will be stored
 * @param params additional parameters for the parser
 * @return 0 if everything went fine, NON 0 if an error took place
 */
int cmdline_parser_ext (int argc, char **argv,
  struct gengetopt_args_info *args_info,
  struct cmdline_parser_params *params);

/**
 * Save the contents of the option struct into an already open FILE stream.
 * @param outfile the stream where to dump options
 * @param args_info the option struct to dump
 * @return 0 if everything went fine, NON 0 if an error took place
 */
int cmdline_parser_dump(FILE *outfile,
  struct gengetopt_args_info *args_info);

/**
 * Save the contents of the option struct into a (text) file.
 * This file can be read by the config file parser (if generated by gengetopt)
 * @param filename the file where to save
 * @param args_info the option struct to save
 * @return 0 if everything went fine, NON 0 if an error took place
 */
int cmdline_parser_file_save(const char *filename,
  struct gengetopt_args_info *args_info);

/**
 * Print the help
 */
void cmdline_parser_print_help(void);
/**
 * Print the version
 */
void cmdline_parser_print_version(void);

/**
 * Initializes all the fields a cmdline_parser_params structure 
 * to their default values
 * @param params the structure to initialize
 */
void cmdline_parser_params_init(struct cmdline_parser_params *params);

/**
 * Allocates dynamically a cmdline_parser_params structure and initializes
 * all its fields to their default values
 * @return the created and initialized cmdline_parser_params structure
 */
struct cmdline_parser_params *cmdline_parser_params_create(void);

/**
 * Initializes the passed gengetopt_args_info structure's fields
 * (also set default values for options that have a default)
 * @param args_info the structure to initialize
 */
void cmdline_parser_init (struct gengetopt_args_info *args_info);
/**
 * Deallocates the string fields of the gengetopt_args_info structure
 * (but does not deallocate the structure itself)
 * @param args_info the structure to deallocate
 */
void cmdline_parser_free (struct gengetopt_args_info *args_info);

/**
 * Checks that all the required options were specified
 * @param args_info the structure to check
 * @param prog_name the name of the program that will be used to print
 *   possible errors
 * @return
 */
int cmdline_parser_required (struct gengetopt_args_info *args_info,
  const char *prog_name);


#ifdef __cplusplus
}
#endif /* __cplusplus */
#endif /* CMDLINE_H */
